## Obtendo um conjuto de dados

In [2]:
!ls

conjunto_de_dados.ipynb  ordf.csv  query.sql


In [3]:
import pandas as pd

In [4]:
exemplo = pd.read_csv('./ordf.csv')

In [6]:
exemplo

Unnamed: 0  a  b  a_or_b
0           0  0  0       0
1           1  0  1       1
2           2  1  0       1
3           3  1  1       1

In [17]:
#  The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
!pip install scikit-learn

/bin/pip:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point


In [12]:
from sklearn.datasets import load_iris

In [13]:
data = load_iris()

In [15]:
iris_df = pd.DataFrame(data.data, columns = data.feature_names)
iris_df['encoded_target'] = data.target

In [16]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     encoded_target  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
145               2  
146               2  
147               2  
148               2  
149               2  

[150 rows x 5 columns]

## Lidando com dados nulos e corrompidos

In [19]:
iris_df.iloc[0,0] = None
iris_df.iloc[0,1] = None
iris_df.iloc[0,2] = None
iris_df.iloc[1,0] = None
iris_df.iloc[4,3] = None
iris_df.iloc[149,2] = None
iris_df.iloc[3,3] = -99999999999999999999
iris_df.iloc[149,2] = "cwevawevberbqb"

In [28]:
iris_df

sepal length (cm)  sepal width (cm) petal length (cm)  \
0                  NaN               NaN               NaN   
1                  NaN               3.0               1.4   
2                  4.7               3.2               1.3   
3                  4.6               3.1               1.5   
4                  5.0               3.6               1.4   
..                 ...               ...               ...   
145                6.7               3.0               5.2   
146                6.3               2.5               5.0   
147                6.5               3.0               5.2   
148                6.2               3.4               5.4   
149                5.9               3.0    cwevawevberbqb   

          petal width (cm)  encoded_target  
0                      0.2               0  
1                      0.2               0  
2                      0.2               0  
3    -99999999999999999999               0  
4                      NaN               0  
..                     ...             ...  
145                    2.3               2  
146                    1.9               2  
147                    2.0               2  
148                    2.3               2  
149                    1.8               2  

[150 rows x 5 columns]

In [21]:
iris_df.isna()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 True              True               True             False   
1                 True             False              False             False   
2                False             False              False             False   
3                False             False              False             False   
4                False             False              False              True   
..                 ...               ...                ...               ...   
145              False             False              False             False   
146              False             False              False             False   
147              False             False              False             False   
148              False             False              False             False   
149              False             False              False             False   

     encoded_target  
0             False  
1             False  
2             False  
3             False  
4             False  
..              ...  
145           False  
146           False  
147           False  
148           False  
149           False  

[150 rows x 5 columns]

In [22]:
iris_df[iris_df.isna().any(axis=1)]

sepal length (cm)  sepal width (cm) petal length (cm) petal width (cm)  \
0                NaN               NaN               NaN              0.2   
1                NaN               3.0               1.4              0.2   
4                5.0               3.6               1.4              NaN   

   encoded_target  
0               0  
1               0  
4               0

In [23]:
iris_df_rem = iris_df.dropna()

In [24]:
iris_df_rem

sepal length (cm)  sepal width (cm) petal length (cm)  \
2                  4.7               3.2               1.3   
3                  4.6               3.1               1.5   
5                  5.4               3.9               1.7   
6                  4.6               3.4               1.4   
7                  5.0               3.4               1.5   
..                 ...               ...               ...   
145                6.7               3.0               5.2   
146                6.3               2.5               5.0   
147                6.5               3.0               5.2   
148                6.2               3.4               5.4   
149                5.9               3.0    cwevawevberbqb   

          petal width (cm)  encoded_target  
2                      0.2               0  
3    -99999999999999999999               0  
5                      0.4               0  
6                      0.3               0  
7                      0.2               0  
..                     ...             ...  
145                    2.3               2  
146                    1.9               2  
147                    2.0               2  
148                    2.3               2  
149                    1.8               2  

[147 rows x 5 columns]

In [30]:
iris_df_mean = iris_df.fillna(iris_df.mean()) # substituir pela média da coluna
iris_df_zero = iris_df.fillna(0) # substituir por zero
iris_df_valores = iris_df.fillna(-999) # substituir por um valor impossível

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [26]:
iris_df_mean

NameError: name 'iris_df_mean' is not defined

In [31]:
iris_df_zero

NameError: name 'iris_df_zero' is not defined

In [32]:
iris_df_valores

NameError: name 'iris_df_valores' is not defined

In [34]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  148 non-null    float64
 1   sepal width (cm)   149 non-null    float64
 2   petal length (cm)  149 non-null    object 
 3   petal width (cm)   149 non-null    object 
 4   encoded_target     150 non-null    int64  
dtypes: float64(2), int64(1), object(2)
memory usage: 6.0+ KB


In [38]:
iris_df = iris_df.fillna(0)

In [39]:
iris_df['petal length (cm)'].unique()

array([0. , 1.4, 1.3, 1.5, 1.7, 1.6, 1.1, 1.2, 1. , 1.9, 4.7, 4.5, 4.9,
       4. , 4.6, 3.3, 3.9, 3.5, 4.2, 3.6, 4.4, 4.1, 4.8, 4.3, 5. , 3.8,
       3.7, 5.1, 3. , 6. , 5.9, 5.6, 5.8, 6.6, 6.3, 6.1, 5.3, 5.5, 6.7,
       6.9, 5.7, 6.4, 5.4, 5.2])

In [40]:
# lidando com dados corrompidos
iris_df  = iris_df[iris_df['petal length (cm)'] != 'cwevawevberbqb'].reset_index(drop=True)

In [41]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  \
0                  0.0               0.0                0.0   
1                  0.0               3.0                1.4   
2                  4.7               3.2                1.3   
3                  4.6               3.1                1.5   
4                  5.0               3.6                1.4   
..                 ...               ...                ...   
144                6.7               3.3                5.7   
145                6.7               3.0                5.2   
146                6.3               2.5                5.0   
147                6.5               3.0                5.2   
148                6.2               3.4                5.4   

          petal width (cm)  encoded_target  
0                      0.2               0  
1                      0.2               0  
2                      0.2               0  
3    -99999999999999999999               0  
4                        0               0  
..                     ...             ...  
144                    2.5               2  
145                    2.3               2  
146                    1.9               2  
147                    2.0               2  
148                    2.3               2  

[149 rows x 5 columns]

In [42]:
iris_df['petal length (cm)'].unique()

array([0. , 1.4, 1.3, 1.5, 1.7, 1.6, 1.1, 1.2, 1. , 1.9, 4.7, 4.5, 4.9,
       4. , 4.6, 3.3, 3.9, 3.5, 4.2, 3.6, 4.4, 4.1, 4.8, 4.3, 5. , 3.8,
       3.7, 5.1, 3. , 6. , 5.9, 5.6, 5.8, 6.6, 6.3, 6.1, 5.3, 5.5, 6.7,
       6.9, 5.7, 6.4, 5.4, 5.2])

In [43]:
iris_df['petal width (cm)'].unique()

array([0.2, -99999999999999999999, 0, 0.4, 0.3, 0.1, 0.5, 0.6, 1.4, 1.5,
       1.3, 1.6, 1.0, 1.1, 1.8, 1.2, 1.7, 2.5, 1.9, 2.1, 2.2, 2.0, 2.4,
       2.3], dtype=object)

In [44]:
# removendo pontos fora da curva
iris_df  = iris_df[iris_df['petal width (cm)'] != -99999999999999999999]

In [45]:
iris_df['petal width (cm)'].unique()

array([0.2, 0, 0.4, 0.3, 0.1, 0.5, 0.6, 1.4, 1.5, 1.3, 1.6, 1.0, 1.1, 1.8,
       1.2, 1.7, 2.5, 1.9, 2.1, 2.2, 2.0, 2.4, 2.3], dtype=object)

## Regularização de dados

In [57]:
import numpy as np
iris_df['artificial'] = np.random.uniform(100, 1000, iris_df.shape[0]).round(2)

/tmp/ipykernel_201549/3055363940.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iris_df['artificial'] = np.random.uniform(100, 1000, iris_df.shape[0]).round(2)


In [58]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm) petal width (cm)  \
0                  0.0               0.0                0.0              0.2   
1                  0.0               3.0                1.4              0.2   
2                  4.7               3.2                1.3              0.2   
4                  5.0               3.6                1.4                0   
5                  5.4               3.9                1.7              0.4   
..                 ...               ...                ...              ...   
144                6.7               3.3                5.7              2.5   
145                6.7               3.0                5.2              2.3   
146                6.3               2.5                5.0              1.9   
147                6.5               3.0                5.2              2.0   
148                6.2               3.4                5.4              2.3   

     encoded_target  arificial  artificial  
0                 0     234.85      552.73  
1                 0     837.43      109.65  
2                 0     937.68      265.97  
4                 0     624.57      523.96  
5                 0     159.77      391.12  
..              ...        ...         ...  
144               2     483.49      965.21  
145               2     135.32      832.00  
146               2     617.71      473.52  
147               2     955.40      146.64  
148               2     444.82      550.07  

[148 rows x 7 columns]

In [59]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

print(scaler.fit(iris_df))

novo_iris_df = scaler.transform(iris_df)

MinMaxScaler()


In [60]:
novo_iris_df = pd.DataFrame(novo_iris_df, columns=iris_df.columns).round(2)

In [61]:
novo_iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 0.00              0.00               0.00              0.08   
1                 0.00              0.68               0.20              0.08   
2                 0.59              0.73               0.19              0.08   
3                 0.63              0.82               0.20              0.00   
4                 0.68              0.89               0.25              0.16   
..                 ...               ...                ...               ...   
143               0.85              0.75               0.83              1.00   
144               0.85              0.68               0.75              0.92   
145               0.80              0.57               0.72              0.76   
146               0.82              0.68               0.75              0.80   
147               0.78              0.77               0.78              0.92   

     encoded_target  arificial  artificial  
0               0.0       0.14        0.50  
1               0.0       0.82        0.00  
2               0.0       0.93        0.18  
3               0.0       0.58        0.47  
4               0.0       0.06        0.32  
..              ...        ...         ...  
143             1.0       0.42        0.96  
144             1.0       0.03        0.81  
145             1.0       0.57        0.41  
146             1.0       0.95        0.04  
147             1.0       0.38        0.50  

[148 rows x 7 columns]

In [62]:
novo_iris_df['encoded_target'].unique()

array([0. , 0.5, 1. ])

In [63]:
novo_iris_df['petal width (cm)'].unique()

array([0.08, 0.  , 0.16, 0.12, 0.04, 0.2 , 0.24, 0.56, 0.6 , 0.52, 0.64,
       0.4 , 0.44, 0.72, 0.48, 0.68, 1.  , 0.76, 0.84, 0.88, 0.8 , 0.96,
       0.92])

In [64]:
novo_iris_df['artificial'].unique()

array([0.5 , 0.  , 0.18, 0.47, 0.32, 0.58, 0.65, 0.29, 0.87, 0.4 , 0.3 ,
       0.35, 0.54, 0.99, 0.53, 0.1 , 0.43, 0.74, 0.23, 0.78, 0.28, 0.6 ,
       0.51, 0.95, 0.75, 0.96, 0.93, 0.02, 0.26, 0.73, 0.38, 0.83, 0.03,
       0.17, 0.01, 0.92, 0.39, 0.27, 0.57, 0.12, 0.05, 1.  , 0.98, 0.84,
       0.76, 0.94, 0.63, 0.36, 0.8 , 0.42, 0.64, 0.14, 0.67, 0.48, 0.25,
       0.22, 0.13, 0.82, 0.56, 0.86, 0.91, 0.44, 0.16, 0.41, 0.72, 0.7 ,
       0.19, 0.62, 0.61, 0.04, 0.07, 0.85, 0.21, 0.15, 0.2 , 0.81])